name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npx semantic-release
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}s
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
